---
# tasks file for hoplacloud.linux_update
- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Remove unattended-upgrades package
  apt:
    name: unattended-upgrades
    state: absent

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: notify reboot is required
  debug:
    msg: "REBOOT REQUIRED"
  when: reboot_required_file.stat.exists
  notify: reboot
