---
# tasks file for hoplacloud.linux_update
- name: Update all packages to the latest version
  apt:
    upgrade: dist
    update_cache: yes

- name: Remove unattended-upgrades package
  apt:
    name: unattended-upgrades
    state: absent

- name: Disable lxcfs
  systemd:
    name: lxcfs
    enabled: no

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: check if a reboot is required
  shell: "[ -f /var/run/reboot-required ]"
  failed_when: False
  register: reboot_required
  changed_when: reboot_required.rc == 0

- name: Notify reboot if ansible connection is local
  debug: msg="Need localhost reboot"
  notify: reboot_normal
  when: reboot_required.changed and ansible_play_hosts != 'localhost'

- name: Notify reboot if ansible connection is local
  debug: msg="Need normal reboot"
  notify: reboot_localhost
  when: reboot_required.changed and ansible_play_hosts == 'localhost'
